// src/lib/country-labels.ts
// 全球主要国家的中心坐标 + 中英文名称
// 仅包含国家级标注，不包含城市和省份

export interface CountryLabel {
  code: string;
  nameEn: string;
  nameZh: string;
  lat: number;
  lon: number;
  importance: number; // 1=大国始终显示, 2=中等国家zoom>=3显示, 3=小国zoom>=4显示
}

export const COUNTRY_LABELS: CountryLabel[] = [
  // ═══ 重要性 1：大国（zoom>=2 即显示） ═══
  { code: 'CN', nameEn: 'China', nameZh: '中国', lat: 35, lon: 104, importance: 1 },
  { code: 'US', nameEn: 'United States', nameZh: '美国', lat: 39, lon: -98, importance: 1 },
  { code: 'RU', nameEn: 'Russia', nameZh: '俄罗斯', lat: 62, lon: 95, importance: 1 },
  { code: 'BR', nameEn: 'Brazil', nameZh: '巴西', lat: -10, lon: -52, importance: 1 },
  { code: 'IN', nameEn: 'India', nameZh: '印度', lat: 22, lon: 79, importance: 1 },
  { code: 'AU', nameEn: 'Australia', nameZh: '澳大利亚', lat: -25, lon: 134, importance: 1 },
  { code: 'CA', nameEn: 'Canada', nameZh: '加拿大', lat: 56, lon: -96, importance: 1 },
  { code: 'ID', nameEn: 'Indonesia', nameZh: '印度尼西亚', lat: -2, lon: 118, importance: 1 },
  { code: 'SA', nameEn: 'Saudi Arabia', nameZh: '沙特阿拉伯', lat: 24, lon: 45, importance: 1 },
  { code: 'AR', nameEn: 'Argentina', nameZh: '阿根廷', lat: -34, lon: -64, importance: 1 },

  // ═══ 重要性 2：中等国家（zoom>=3 显示） ═══
  { code: 'JP', nameEn: 'Japan', nameZh: '日本', lat: 36, lon: 138, importance: 2 },
  { code: 'KR', nameEn: 'South Korea', nameZh: '韩国', lat: 36, lon: 128, importance: 2 },
  { code: 'GB', nameEn: 'United Kingdom', nameZh: '英国', lat: 54, lon: -2, importance: 2 },
  { code: 'FR', nameEn: 'France', nameZh: '法国', lat: 47, lon: 2, importance: 2 },
  { code: 'DE', nameEn: 'Germany', nameZh: '德国', lat: 51, lon: 10, importance: 2 },
  { code: 'IT', nameEn: 'Italy', nameZh: '意大利', lat: 42, lon: 12, importance: 2 },
  { code: 'ES', nameEn: 'Spain', nameZh: '西班牙', lat: 40, lon: -4, importance: 2 },
  { code: 'MX', nameEn: 'Mexico', nameZh: '墨西哥', lat: 23, lon: -102, importance: 2 },
  { code: 'EG', nameEn: 'Egypt', nameZh: '埃及', lat: 27, lon: 30, importance: 2 },
  { code: 'ZA', nameEn: 'South Africa', nameZh: '南非', lat: -29, lon: 25, importance: 2 },
  { code: 'NG', nameEn: 'Nigeria', nameZh: '尼日利亚', lat: 10, lon: 8, importance: 2 },
  { code: 'TR', nameEn: 'Turkey', nameZh: '土耳其', lat: 39, lon: 35, importance: 2 },
  { code: 'IR', nameEn: 'Iran', nameZh: '伊朗', lat: 33, lon: 53, importance: 2 },
  { code: 'PK', nameEn: 'Pakistan', nameZh: '巴基斯坦', lat: 30, lon: 70, importance: 2 },
  { code: 'TH', nameEn: 'Thailand', nameZh: '泰国', lat: 15, lon: 101, importance: 2 },
  { code: 'VN', nameEn: 'Vietnam', nameZh: '越南', lat: 16, lon: 106, importance: 2 },
  { code: 'MY', nameEn: 'Malaysia', nameZh: '马来西亚', lat: 4, lon: 109, importance: 2 },
  { code: 'PH', nameEn: 'Philippines', nameZh: '菲律宾', lat: 13, lon: 122, importance: 2 },
  { code: 'AE', nameEn: 'UAE', nameZh: '阿联酋', lat: 24, lon: 54, importance: 2 },
  { code: 'CL', nameEn: 'Chile', nameZh: '智利', lat: -33, lon: -71, importance: 2 },
  { code: 'CO', nameEn: 'Colombia', nameZh: '哥伦比亚', lat: 4, lon: -74, importance: 2 },
  { code: 'PE', nameEn: 'Peru', nameZh: '秘鲁', lat: -10, lon: -76, importance: 2 },
  { code: 'SE', nameEn: 'Sweden', nameZh: '瑞典', lat: 62, lon: 15, importance: 2 },
  { code: 'NO', nameEn: 'Norway', nameZh: '挪威', lat: 64, lon: 12, importance: 2 },
  { code: 'PL', nameEn: 'Poland', nameZh: '波兰', lat: 52, lon: 20, importance: 2 },
  { code: 'UA', nameEn: 'Ukraine', nameZh: '乌克兰', lat: 49, lon: 32, importance: 2 },
  { code: 'KZ', nameEn: 'Kazakhstan', nameZh: '哈萨克斯坦', lat: 48, lon: 67, importance: 2 },
  { code: 'DZ', nameEn: 'Algeria', nameZh: '阿尔及利亚', lat: 28, lon: 2, importance: 2 },
  { code: 'LY', nameEn: 'Libya', nameZh: '利比亚', lat: 27, lon: 17, importance: 2 },
  { code: 'ET', nameEn: 'Ethiopia', nameZh: '埃塞俄比亚', lat: 9, lon: 39, importance: 2 },
  { code: 'KE', nameEn: 'Kenya', nameZh: '肯尼亚', lat: 0, lon: 38, importance: 2 },
  { code: 'TZ', nameEn: 'Tanzania', nameZh: '坦桑尼亚', lat: -6, lon: 35, importance: 2 },
  { code: 'MM', nameEn: 'Myanmar', nameZh: '缅甸', lat: 20, lon: 97, importance: 2 },
  { code: 'NZ', nameEn: 'New Zealand', nameZh: '新西兰', lat: -42, lon: 174, importance: 2 },
  { code: 'MN', nameEn: 'Mongolia', nameZh: '蒙古', lat: 47, lon: 104, importance: 2 },

  // ═══ 重要性 3：较小国家（zoom>=4 显示） ═══
  { code: 'PT', nameEn: 'Portugal', nameZh: '葡萄牙', lat: 39, lon: -8, importance: 3 },
  { code: 'NL', nameEn: 'Netherlands', nameZh: '荷兰', lat: 52, lon: 5, importance: 3 },
  { code: 'BE', nameEn: 'Belgium', nameZh: '比利时', lat: 51, lon: 4, importance: 3 },
  { code: 'GR', nameEn: 'Greece', nameZh: '希腊', lat: 39, lon: 22, importance: 3 },
  { code: 'IE', nameEn: 'Ireland', nameZh: '爱尔兰', lat: 53, lon: -8, importance: 3 },
  { code: 'DK', nameEn: 'Denmark', nameZh: '丹麦', lat: 56, lon: 10, importance: 3 },
  { code: 'FI', nameEn: 'Finland', nameZh: '芬兰', lat: 64, lon: 26, importance: 3 },
  { code: 'SG', nameEn: 'Singapore', nameZh: '新加坡', lat: 1.3, lon: 104, importance: 3 },
  { code: 'IL', nameEn: 'Israel', nameZh: '以色列', lat: 31, lon: 35, importance: 3 },
  { code: 'OM', nameEn: 'Oman', nameZh: '阿曼', lat: 21, lon: 57, importance: 3 },
  { code: 'QA', nameEn: 'Qatar', nameZh: '卡塔尔', lat: 25, lon: 51, importance: 3 },
  { code: 'KW', nameEn: 'Kuwait', nameZh: '科威特', lat: 29, lon: 48, importance: 3 },
  { code: 'BH', nameEn: 'Bahrain', nameZh: '巴林', lat: 26, lon: 50.5, importance: 3 },
  { code: 'JO', nameEn: 'Jordan', nameZh: '约旦', lat: 31, lon: 36, importance: 3 },
  { code: 'LK', nameEn: 'Sri Lanka', nameZh: '斯里兰卡', lat: 7.5, lon: 81, importance: 3 },
  { code: 'BD', nameEn: 'Bangladesh', nameZh: '孟加拉国', lat: 24, lon: 90, importance: 3 },
  { code: 'KH', nameEn: 'Cambodia', nameZh: '柬埔寨', lat: 13, lon: 105, importance: 3 },
  { code: 'GH', nameEn: 'Ghana', nameZh: '加纳', lat: 8, lon: -1.5, importance: 3 },
  { code: 'SN', nameEn: 'Senegal', nameZh: '塞内加尔', lat: 14, lon: -14, importance: 3 },
  { code: 'CI', nameEn: "Cote d'Ivoire", nameZh: '科特迪瓦', lat: 7.5, lon: -5.5, importance: 3 },
  { code: 'MZ', nameEn: 'Mozambique', nameZh: '莫桑比克', lat: -18, lon: 35, importance: 3 },
  { code: 'MG', nameEn: 'Madagascar', nameZh: '马达加斯加', lat: -19, lon: 47, importance: 3 },
  { code: 'AO', nameEn: 'Angola', nameZh: '安哥拉', lat: -12, lon: 18, importance: 3 },
  { code: 'CD', nameEn: 'DR Congo', nameZh: '刚果(金)', lat: -3, lon: 24, importance: 3 },
  { code: 'SD', nameEn: 'Sudan', nameZh: '苏丹', lat: 15, lon: 30, importance: 3 },
  { code: 'MA', nameEn: 'Morocco', nameZh: '摩洛哥', lat: 32, lon: -6, importance: 3 },
  { code: 'TN', nameEn: 'Tunisia', nameZh: '突尼斯', lat: 34, lon: 9, importance: 3 },
  { code: 'IQ', nameEn: 'Iraq', nameZh: '伊拉克', lat: 33, lon: 44, importance: 3 },
  { code: 'AF', nameEn: 'Afghanistan', nameZh: '阿富汗', lat: 34, lon: 66, importance: 3 },
  { code: 'UZ', nameEn: 'Uzbekistan', nameZh: '乌兹别克斯坦', lat: 41, lon: 65, importance: 3 },
  { code: 'CU', nameEn: 'Cuba', nameZh: '古巴', lat: 22, lon: -80, importance: 3 },
  { code: 'VE', nameEn: 'Venezuela', nameZh: '委内瑞拉', lat: 7, lon: -66, importance: 3 },
  { code: 'EC', nameEn: 'Ecuador', nameZh: '厄瓜多尔', lat: -1.5, lon: -78, importance: 3 },
  { code: 'PA', nameEn: 'Panama', nameZh: '巴拿马', lat: 9, lon: -80, importance: 3 },
  { code: 'CR', nameEn: 'Costa Rica', nameZh: '哥斯达黎加', lat: 10, lon: -84, importance: 3 },
  { code: 'PG', nameEn: 'Papua New Guinea', nameZh: '巴布亚新几内亚', lat: -6, lon: 147, importance: 3 },
  { code: 'FJ', nameEn: 'Fiji', nameZh: '斐济', lat: -18, lon: 179, importance: 3 },
  { code: 'IS', nameEn: 'Iceland', nameZh: '冰岛', lat: 65, lon: -18, importance: 3 },
  { code: 'BY', nameEn: 'Belarus', nameZh: '白俄罗斯', lat: 53, lon: 28, importance: 3 },
  { code: 'RO', nameEn: 'Romania', nameZh: '罗马尼亚', lat: 46, lon: 25, importance: 3 },
  { code: 'CZ', nameEn: 'Czechia', nameZh: '捷克', lat: 50, lon: 15, importance: 3 },
  { code: 'AT', nameEn: 'Austria', nameZh: '奥地利', lat: 48, lon: 14, importance: 3 },
  { code: 'CH', nameEn: 'Switzerland', nameZh: '瑞士', lat: 47, lon: 8, importance: 3 },
  { code: 'HU', nameEn: 'Hungary', nameZh: '匈牙利', lat: 47, lon: 20, importance: 3 },
  { code: 'HR', nameEn: 'Croatia', nameZh: '克罗地亚', lat: 45, lon: 16, importance: 3 },
  { code: 'UG', nameEn: 'Uganda', nameZh: '乌干达', lat: 1.5, lon: 32, importance: 3 },
  { code: 'BO', nameEn: 'Bolivia', nameZh: '玻利维亚', lat: -17, lon: -65, importance: 3 },
  { code: 'UY', nameEn: 'Uruguay', nameZh: '乌拉圭', lat: -33, lon: -56, importance: 3 },
  { code: 'DJ', nameEn: 'Djibouti', nameZh: '吉布提', lat: 11.5, lon: 43, importance: 3 },
  { code: 'SC', nameEn: 'Seychelles', nameZh: '塞舌尔', lat: -4.5, lon: 55.5, importance: 3 },
  { code: 'MU', nameEn: 'Mauritius', nameZh: '毛里求斯', lat: -20, lon: 57.5, importance: 3 },
  { code: 'MV', nameEn: 'Maldives', nameZh: '马尔代夫', lat: 3.2, lon: 73, importance: 3 },
  { code: 'CM', nameEn: 'Cameroon', nameZh: '喀麦隆', lat: 6, lon: 12, importance: 3 },
  { code: 'GA', nameEn: 'Gabon', nameZh: '加蓬', lat: -0.5, lon: 11.7, importance: 3 },

  // ═══ 大洋标注 ═══
  { code: '_PAC', nameEn: 'Pacific Ocean', nameZh: '太平洋', lat: 0, lon: -150, importance: 1 },
  { code: '_ATL', nameEn: 'Atlantic Ocean', nameZh: '大西洋', lat: 15, lon: -35, importance: 1 },
  { code: '_IND', nameEn: 'Indian Ocean', nameZh: '印度洋', lat: -15, lon: 75, importance: 1 },
  { code: '_ARC', nameEn: 'Arctic Ocean', nameZh: '北冰洋', lat: 75, lon: 0, importance: 2 },
  { code: '_SOU', nameEn: 'Southern Ocean', nameZh: '南冰洋', lat: -65, lon: 0, importance: 2 },
];
