// src/lib/sovereign-routes.ts
// 从 Excel 直接生成，海缆名称与 Excel 完全一致，去重结果精确

export const BRICS_MEMBERS = new Set([
  '中国','俄罗斯','印度','巴西','南非',
  '沙特阿拉伯','埃及','阿联酋','伊朗','阿根廷','埃塞俄比亚',
]);

export const BRICS_PARTNERS = new Set([
  '印度尼西亚','马来西亚','泰国','越南','尼日利亚',
  '古巴','白俄罗斯','哈萨克斯坦','乌兹别克斯坦','玻利维亚','乌干达',
]);

export const NODE_COORDS: Record<string, [number, number]> = {
  '巴西':       [-51.9,-14.2], '俄罗斯':     [105,61.5],  '印度':       [79,21],
  '中国':       [104,35],      '南非':       [25,-30],    '沙特阿拉伯': [45,24],
  '埃及':       [30,26],       '阿联酋':     [54,24],     '伊朗':       [53,33],
  '印度尼西亚': [118,-5],      '马来西亚':   [109,4],     '泰国':       [101,15],
  '越南':       [106,14],      '尼日利亚':   [8,9],       '新加坡':     [104,1.3],
  '日本':       [138,36],      '菲律宾':     [122,13],    '韩国':       [128,37],
  '喀麦隆':     [12,4],        '塞舌尔':     [55.5,-4.7], '索马里':     [46,5],
  '坦桑尼亚':   [35,-6],       '也门':       [48,15.5],
};

export type SafetyLevel = '相对低暴露优先路径' | '较优备选路径' | '中等暴露路径' | '高暴露路径';

export interface SovereignRoute {
  id: string; from: string; to: string; path: string; nodes: string[];
  cables: string; riskScores: string; maxRisk: number; avgRisk: number;
  segments: number; safety: SafetyLevel;
}

// Badge 样式：深色半透明底 + 彩色描边文字
export function safetyCfg(safety: SafetyLevel): { bg: string; text: string; border: string; label: string } {
  const m: Record<SafetyLevel, { bg: string; text: string; border: string; label: string }> = {
    '相对低暴露优先路径': { bg: 'rgba(16,112,86,.25)',  text: '#4ade80', border: 'rgba(74,222,128,.3)',  label: '低风险'   },
    '较优备选路径':       { bg: 'rgba(20,100,76,.2)',   text: '#34d399', border: 'rgba(52,211,153,.25)', label: '较优备选' },
    '中等暴露路径':       { bg: 'rgba(120,90,10,.25)',  text: '#fbbf24', border: 'rgba(251,191,36,.3)',  label: '中等风险' },
    '高暴露路径':         { bg: 'rgba(120,20,20,.25)',  text: '#f87171', border: 'rgba(248,113,113,.3)', label: '高暴露'   },
  };
  return m[safety] ?? { bg: 'rgba(40,40,60,.3)', text: '#94a3b8', border: 'rgba(148,163,184,.2)', label: safety };
}

export function riskColor(score: number): string {
  if (score <= 20) return '#0F6E56';
  if (score <= 40) return '#639922';
  if (score <= 60) return '#BA7517';
  if (score <= 75) return '#D85A30';
  return '#A32D2D';
}

// 26 条保留海缆的标准名称（与 Excel 完全一致）
export const CANONICAL_CABLE_NAMES: string[] = [
  'ALPHA',
  'Asia Connect Cable-1 (ACC-1)',
  'Asia Direct Cable (ADC)',
  'Asia Link Cable (ALC)',
  'Asia Submarine-cable Express (ASE)/Cahaya Malaysia',
  'Batam Dumai Melaka (BDM)',
  'Batam Sarawak Internet Cable System (BaSICS)',
  'Batam Singapore Cable System (BSCS)',
  'Batam-Rengit Cable System (BRCS)',
  'Bridge One',
  'BtoBE',
  'Dumai-Melaka Cable System (DMCS)',
  'Hokkaido-Sakhalin Cable System (HSCS)',
  'INSICA',
  'Indonesia Global Gateway (IGG) System',
  'MIST',
  'MYUS',
  'Nigeria Cameroon Submarine Cable System (NCSCS)',
  'PEACE Cable',
  'Russia-Japan Cable Network (RJCN)',
  'SEA-H2X',
  'SEACOM',
  'South Atlantic Inter Link (SAIL)',
  'TGN-IA2',
  'Thailand-Indonesia-Singapore (TIS)',
  'Vietnam-Singapore Cable System (VTS)',
];

export const SOVEREIGN_ROUTES: SovereignRoute[] = [
  { id: "阿联酋|泰国|阿联酋 → 新加坡 → 泰国", from: "阿联酋", to: "泰国", path: "阿联酋 → 新加坡 → 泰国", nodes: ["阿联酋", "新加坡", "泰国"], cables: "PEACE Cable | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "8 | 33 | 55", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "阿联酋|印度尼西亚|阿联酋 → 新加坡 → 印度尼西亚", from: "阿联酋", to: "印度尼西亚", path: "阿联酋 → 新加坡 → 印度尼西亚", nodes: ["阿联酋", "新加坡", "印度尼西亚"], cables: "PEACE Cable | Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA", riskScores: "8 | 33 | 33 | 33 | 30", maxRisk: 33, avgRisk: 27, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "阿联酋|越南|阿联酋 → 新加坡 → 越南", from: "阿联酋", to: "越南", path: "阿联酋 → 新加坡 → 越南", nodes: ["阿联酋", "新加坡", "越南"], cables: "PEACE Cable | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "8 | 33 | 55 | 30", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "埃及|阿联酋|埃及 → 塞舌尔 → 阿联酋", from: "埃及", to: "阿联酋", path: "埃及 → 塞舌尔 → 阿联酋", nodes: ["埃及", "塞舌尔", "阿联酋"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "埃及|阿联酋|埃及 → 索马里 → 阿联酋", from: "埃及", to: "阿联酋", path: "埃及 → 索马里 → 阿联酋", nodes: ["埃及", "索马里", "阿联酋"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "埃及|马来西亚|埃及 → 新加坡 → 马来西亚", from: "埃及", to: "马来西亚", path: "埃及 → 新加坡 → 马来西亚", nodes: ["埃及", "新加坡", "马来西亚"], cables: "PEACE Cable | Asia Link Cable (ALC)", riskScores: "8 | 33", maxRisk: 33, avgRisk: 21, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "埃及|泰国|埃及 → 新加坡 → 泰国", from: "埃及", to: "泰国", path: "埃及 → 新加坡 → 泰国", nodes: ["埃及", "新加坡", "泰国"], cables: "PEACE Cable | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "8 | 33 | 55", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "埃及|印度尼西亚|埃及 → 新加坡 → 印度尼西亚", from: "埃及", to: "印度尼西亚", path: "埃及 → 新加坡 → 印度尼西亚", nodes: ["埃及", "新加坡", "印度尼西亚"], cables: "PEACE Cable | Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA", riskScores: "8 | 33 | 33 | 33 | 30", maxRisk: 33, avgRisk: 27, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "埃及|越南|埃及 → 新加坡 → 越南", from: "埃及", to: "越南", path: "埃及 → 新加坡 → 越南", nodes: ["埃及", "新加坡", "越南"], cables: "PEACE Cable | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "8 | 33 | 55 | 30", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "巴西|尼日利亚|巴西 → 喀麦隆 → 尼日利亚", from: "巴西", to: "尼日利亚", path: "巴西 → 喀麦隆 → 尼日利亚", nodes: ["巴西", "喀麦隆", "尼日利亚"], cables: "South Atlantic Inter Link (SAIL) | Nigeria Cameroon Submarine Cable System (NCSCS)", riskScores: "19 | 19", maxRisk: 19, avgRisk: 19, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "俄罗斯|阿联酋|俄罗斯 → 日本 → 新加坡 → 阿联酋", from: "俄罗斯", to: "阿联酋", path: "俄罗斯 → 日本 → 新加坡 → 阿联酋", nodes: ["俄罗斯", "日本", "新加坡", "阿联酋"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | PEACE Cable", riskScores: "71 | 71 | 71 | 61 | 61 | 8", maxRisk: 71, avgRisk: 57, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|埃及|俄罗斯 → 日本 → 新加坡 → 埃及", from: "俄罗斯", to: "埃及", path: "俄罗斯 → 日本 → 新加坡 → 埃及", nodes: ["俄罗斯", "日本", "新加坡", "埃及"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | PEACE Cable", riskScores: "71 | 71 | 71 | 61 | 61 | 8", maxRisk: 71, avgRisk: 57, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 菲律宾 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 菲律宾 → 马来西亚", nodes: ["俄罗斯", "日本", "菲律宾", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | SEA-H2X | MYUS | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "71 | 71 | 71 | 61 | 71 | 50 | 36 | 61 | 71", maxRisk: 71, avgRisk: 63, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 马来西亚", nodes: ["俄罗斯", "日本", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "71 | 71 | 71", maxRisk: 71, avgRisk: 71, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 泰国 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 泰国 → 马来西亚", nodes: ["俄罗斯", "日本", "泰国", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "71 | 71 | 71 | 19", maxRisk: 71, avgRisk: 58, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 新加坡 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 新加坡 → 马来西亚", nodes: ["俄罗斯", "日本", "新加坡", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | Asia Link Cable (ALC)", riskScores: "71 | 71 | 71 | 61 | 61 | 33", maxRisk: 71, avgRisk: 61, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 越南 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 越南 → 马来西亚", nodes: ["俄罗斯", "日本", "越南", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "71 | 71 | 71 | 61 | 33 | 30", maxRisk: 71, avgRisk: 56, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|马来西亚|俄罗斯 → 日本 → 中国 → 马来西亚", from: "俄罗斯", to: "马来西亚", path: "俄罗斯 → 日本 → 中国 → 马来西亚", nodes: ["俄罗斯", "日本", "中国", "马来西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | TGN-IA2 | Asia Link Cable (ALC) | SEA-H2X | BtoBE", riskScores: "71 | 71 | 71 | 61 | 33 | 19 | 44", maxRisk: 71, avgRisk: 53, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|沙特阿拉伯|俄罗斯 → 日本 → 新加坡 → 沙特阿拉伯", from: "俄罗斯", to: "沙特阿拉伯", path: "俄罗斯 → 日本 → 新加坡 → 沙特阿拉伯", nodes: ["俄罗斯", "日本", "新加坡", "沙特阿拉伯"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | PEACE Cable", riskScores: "71 | 71 | 71 | 61 | 61 | 8", maxRisk: 71, avgRisk: 57, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 菲律宾 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 菲律宾 → 泰国", nodes: ["俄罗斯", "日本", "菲律宾", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "71 | 71 | 71 | 61 | 71 | 71 | 36", maxRisk: 71, avgRisk: 65, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 马来西亚 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 马来西亚 → 泰国", nodes: ["俄罗斯", "日本", "马来西亚", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | SEA-H2X", riskScores: "71 | 71 | 71 | 19", maxRisk: 71, avgRisk: 58, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 泰国", nodes: ["俄罗斯", "日本", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC)", riskScores: "71 | 71 | 71", maxRisk: 71, avgRisk: 71, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 新加坡 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 新加坡 → 泰国", nodes: ["俄罗斯", "日本", "新加坡", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "71 | 71 | 71 | 61 | 61 | 33 | 55", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 越南 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 越南 → 泰国", nodes: ["俄罗斯", "日本", "越南", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "71 | 71 | 71 | 61 | 55 | 30", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|泰国|俄罗斯 → 日本 → 中国 → 泰国", from: "俄罗斯", to: "泰国", path: "俄罗斯 → 日本 → 中国 → 泰国", nodes: ["俄罗斯", "日本", "中国", "泰国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | TGN-IA2 | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "71 | 71 | 71 | 61 | 55 | 19", maxRisk: 71, avgRisk: 58, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|印度|俄罗斯 → 日本 → 泰国 → 印度", from: "俄罗斯", to: "印度", path: "俄罗斯 → 日本 → 泰国 → 印度", nodes: ["俄罗斯", "日本", "泰国", "印度"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | MIST", riskScores: "71 | 71 | 71 | 47", maxRisk: 71, avgRisk: 65, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|印度尼西亚|俄罗斯 → 日本 → 菲律宾 → 印度尼西亚", from: "俄罗斯", to: "印度尼西亚", path: "俄罗斯 → 日本 → 菲律宾 → 印度尼西亚", nodes: ["俄罗斯", "日本", "菲律宾", "印度尼西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Connect Cable-1 (ACC-1) | MYUS", riskScores: "71 | 71 | 71 | 61 | 71 | 61 | 61", maxRisk: 71, avgRisk: 67, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|印度尼西亚|俄罗斯 → 日本 → 马来西亚 → 印度尼西亚", from: "俄罗斯", to: "印度尼西亚", path: "俄罗斯 → 日本 → 马来西亚 → 印度尼西亚", nodes: ["俄罗斯", "日本", "马来西亚", "印度尼西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Dumai-Melaka Cable System (DMCS) | Batam Dumai Melaka (BDM) | Batam-Rengit Cable System (BRCS) | Batam Sarawak Internet Cable System (BaSICS)", riskScores: "71 | 71 | 71 | 33 | 19 | 30 | 30", maxRisk: 71, avgRisk: 46, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|印度尼西亚|俄罗斯 → 日本 → 泰国 → 印度尼西亚", from: "俄罗斯", to: "印度尼西亚", path: "俄罗斯 → 日本 → 泰国 → 印度尼西亚", nodes: ["俄罗斯", "日本", "泰国", "印度尼西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | Thailand-Indonesia-Singapore (TIS)", riskScores: "71 | 71 | 71 | 33", maxRisk: 71, avgRisk: 62, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|印度尼西亚|俄罗斯 → 日本 → 新加坡 → 印度尼西亚", from: "俄罗斯", to: "印度尼西亚", path: "俄罗斯 → 日本 → 新加坡 → 印度尼西亚", nodes: ["俄罗斯", "日本", "新加坡", "印度尼西亚"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA", riskScores: "71 | 71 | 71 | 61 | 61 | 33 | 33 | 33 | 30", maxRisk: 71, avgRisk: 52, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 菲律宾 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 菲律宾 → 越南", nodes: ["俄罗斯", "日本", "菲律宾", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | ALPHA", riskScores: "71 | 71 | 71 | 61 | 71 | 50 | 71 | 61", maxRisk: 71, avgRisk: 66, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 韩国 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 韩国 → 越南", nodes: ["俄罗斯", "日本", "韩国", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | ALPHA | Bridge One | ALPHA", riskScores: "71 | 71 | 61 | 61 | 61", maxRisk: 71, avgRisk: 65, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 马来西亚 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 马来西亚 → 越南", nodes: ["俄罗斯", "日本", "马来西亚", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "71 | 71 | 71 | 33 | 30", maxRisk: 71, avgRisk: 55, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 泰国 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 泰国 → 越南", nodes: ["俄罗斯", "日本", "泰国", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "71 | 71 | 71 | 55 | 30", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 新加坡 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 新加坡 → 越南", nodes: ["俄罗斯", "日本", "新加坡", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "71 | 71 | 71 | 61 | 61 | 33 | 55 | 30", maxRisk: 71, avgRisk: 57, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 越南", nodes: ["俄罗斯", "日本", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA", riskScores: "71 | 71 | 71 | 61", maxRisk: 71, avgRisk: 69, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|越南|俄罗斯 → 日本 → 中国 → 越南", from: "俄罗斯", to: "越南", path: "俄罗斯 → 日本 → 中国 → 越南", nodes: ["俄罗斯", "日本", "中国", "越南"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | TGN-IA2 | Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "71 | 71 | 71 | 61 | 33 | 55", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 菲律宾 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 菲律宾 → 中国", nodes: ["俄罗斯", "日本", "菲律宾", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "71 | 71 | 71 | 61 | 71 | 50 | 71 | 36", maxRisk: 71, avgRisk: 63, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 马来西亚 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 马来西亚 → 中国", nodes: ["俄罗斯", "日本", "马来西亚", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | SEA-H2X | BtoBE", riskScores: "71 | 71 | 71 | 33 | 19 | 44", maxRisk: 71, avgRisk: 52, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 泰国 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 泰国 → 中国", nodes: ["俄罗斯", "日本", "泰国", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "71 | 71 | 71 | 55 | 19", maxRisk: 71, avgRisk: 57, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 新加坡 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 新加坡 → 中国", nodes: ["俄罗斯", "日本", "新加坡", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | TGN-IA2 | Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "71 | 71 | 71 | 61 | 61 | 33 | 55", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 越南 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 越南 → 中国", nodes: ["俄罗斯", "日本", "越南", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | ALPHA | Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "71 | 71 | 71 | 61 | 33 | 55", maxRisk: 71, avgRisk: 60, segments: 3, safety: "高暴露路径" as SafetyLevel },
  { id: "俄罗斯|中国|俄罗斯 → 日本 → 中国", from: "俄罗斯", to: "中国", path: "俄罗斯 → 日本 → 中国", nodes: ["俄罗斯", "日本", "中国"], cables: "Russia-Japan Cable Network (RJCN) | Hokkaido-Sakhalin Cable System (HSCS) | Asia Direct Cable (ADC) | TGN-IA2", riskScores: "71 | 71 | 71 | 61", maxRisk: 71, avgRisk: 69, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 菲律宾 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 菲律宾 → 越南", nodes: ["马来西亚", "菲律宾", "越南"], cables: "Asia Link Cable (ALC) | SEA-H2X | MYUS | Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | ALPHA", riskScores: "50 | 36 | 61 | 71 | 50 | 71 | 61", maxRisk: 71, avgRisk: 57, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 日本 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 日本 → 越南", nodes: ["马来西亚", "日本", "越南"], cables: "Asia Submarine-cable Express (ASE)/Cahaya Malaysia | Asia Direct Cable (ADC) | ALPHA", riskScores: "71 | 71 | 61", maxRisk: 71, avgRisk: 68, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 泰国 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 泰国 → 越南", nodes: ["马来西亚", "泰国", "越南"], cables: "SEA-H2X | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "19 | 55 | 30", maxRisk: 55, avgRisk: 35, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 新加坡 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 新加坡 → 越南", nodes: ["马来西亚", "新加坡", "越南"], cables: "Asia Link Cable (ALC) | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 33 | 55 | 30", maxRisk: 55, avgRisk: 38, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 越南", nodes: ["马来西亚", "越南"], cables: "Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 30", maxRisk: 33, avgRisk: 32, segments: 1, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "马来西亚|越南|马来西亚 → 中国 → 越南", from: "马来西亚", to: "越南", path: "马来西亚 → 中国 → 越南", nodes: ["马来西亚", "中国", "越南"], cables: "Asia Link Cable (ALC) | SEA-H2X | BtoBE | Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "33 | 19 | 44 | 33 | 55", maxRisk: 55, avgRisk: 37, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "沙特阿拉伯|阿联酋|沙特阿拉伯 → 塞舌尔 → 阿联酋", from: "沙特阿拉伯", to: "阿联酋", path: "沙特阿拉伯 → 塞舌尔 → 阿联酋", nodes: ["沙特阿拉伯", "塞舌尔", "阿联酋"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|阿联酋|沙特阿拉伯 → 索马里 → 阿联酋", from: "沙特阿拉伯", to: "阿联酋", path: "沙特阿拉伯 → 索马里 → 阿联酋", nodes: ["沙特阿拉伯", "索马里", "阿联酋"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|埃及|沙特阿拉伯 → 塞舌尔 → 埃及", from: "沙特阿拉伯", to: "埃及", path: "沙特阿拉伯 → 塞舌尔 → 埃及", nodes: ["沙特阿拉伯", "塞舌尔", "埃及"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|埃及|沙特阿拉伯 → 索马里 → 埃及", from: "沙特阿拉伯", to: "埃及", path: "沙特阿拉伯 → 索马里 → 埃及", nodes: ["沙特阿拉伯", "索马里", "埃及"], cables: "PEACE Cable | PEACE Cable", riskScores: "8 | 8", maxRisk: 8, avgRisk: 8, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|马来西亚|沙特阿拉伯 → 新加坡 → 马来西亚", from: "沙特阿拉伯", to: "马来西亚", path: "沙特阿拉伯 → 新加坡 → 马来西亚", nodes: ["沙特阿拉伯", "新加坡", "马来西亚"], cables: "PEACE Cable | Asia Link Cable (ALC)", riskScores: "8 | 33", maxRisk: 33, avgRisk: 21, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|泰国|沙特阿拉伯 → 新加坡 → 泰国", from: "沙特阿拉伯", to: "泰国", path: "沙特阿拉伯 → 新加坡 → 泰国", nodes: ["沙特阿拉伯", "新加坡", "泰国"], cables: "PEACE Cable | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "8 | 33 | 55", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "沙特阿拉伯|印度尼西亚|沙特阿拉伯 → 新加坡 → 印度尼西亚", from: "沙特阿拉伯", to: "印度尼西亚", path: "沙特阿拉伯 → 新加坡 → 印度尼西亚", nodes: ["沙特阿拉伯", "新加坡", "印度尼西亚"], cables: "PEACE Cable | Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA", riskScores: "8 | 33 | 33 | 33 | 30", maxRisk: 33, avgRisk: 27, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "沙特阿拉伯|越南|沙特阿拉伯 → 新加坡 → 越南", from: "沙特阿拉伯", to: "越南", path: "沙特阿拉伯 → 新加坡 → 越南", nodes: ["沙特阿拉伯", "新加坡", "越南"], cables: "PEACE Cable | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "8 | 33 | 55 | 30", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|马来西亚|泰国 → 马来西亚", from: "泰国", to: "马来西亚", path: "泰国 → 马来西亚", nodes: ["泰国", "马来西亚"], cables: "SEA-H2X", riskScores: "19", maxRisk: 19, avgRisk: 19, segments: 1, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "泰国|马来西亚|泰国 → 日本 → 马来西亚", from: "泰国", to: "马来西亚", path: "泰国 → 日本 → 马来西亚", nodes: ["泰国", "日本", "马来西亚"], cables: "Asia Direct Cable (ADC) | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "71 | 71", maxRisk: 71, avgRisk: 71, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "泰国|马来西亚|泰国 → 新加坡 → 马来西亚", from: "泰国", to: "马来西亚", path: "泰国 → 新加坡 → 马来西亚", nodes: ["泰国", "新加坡", "马来西亚"], cables: "Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC) | Asia Link Cable (ALC)", riskScores: "33 | 55 | 33", maxRisk: 55, avgRisk: 40, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|马来西亚|泰国 → 越南 → 马来西亚", from: "泰国", to: "马来西亚", path: "泰国 → 越南 → 马来西亚", nodes: ["泰国", "越南", "马来西亚"], cables: "Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS) | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "55 | 30 | 33 | 30", maxRisk: 55, avgRisk: 37, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|马来西亚|泰国 → 中国 → 马来西亚", from: "泰国", to: "马来西亚", path: "泰国 → 中国 → 马来西亚", nodes: ["泰国", "中国", "马来西亚"], cables: "Asia Direct Cable (ADC) | SEA-H2X | Asia Link Cable (ALC) | SEA-H2X | BtoBE", riskScores: "55 | 19 | 33 | 19 | 44", maxRisk: 55, avgRisk: 34, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|越南|泰国 → 马来西亚 → 越南", from: "泰国", to: "越南", path: "泰国 → 马来西亚 → 越南", nodes: ["泰国", "马来西亚", "越南"], cables: "SEA-H2X | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "19 | 33 | 30", maxRisk: 33, avgRisk: 27, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "泰国|越南|泰国 → 日本 → 越南", from: "泰国", to: "越南", path: "泰国 → 日本 → 越南", nodes: ["泰国", "日本", "越南"], cables: "Asia Direct Cable (ADC) | Asia Direct Cable (ADC) | ALPHA", riskScores: "71 | 71 | 61", maxRisk: 71, avgRisk: 68, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "泰国|越南|泰国 → 新加坡 → 越南", from: "泰国", to: "越南", path: "泰国 → 新加坡 → 越南", nodes: ["泰国", "新加坡", "越南"], cables: "Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC) | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 55 | 33 | 55 | 30", maxRisk: 55, avgRisk: 41, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|越南|泰国 → 越南", from: "泰国", to: "越南", path: "泰国 → 越南", nodes: ["泰国", "越南"], cables: "Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "55 | 30", maxRisk: 55, avgRisk: 43, segments: 1, safety: "中等暴露路径" as SafetyLevel },
  { id: "泰国|越南|泰国 → 中国 → 越南", from: "泰国", to: "越南", path: "泰国 → 中国 → 越南", nodes: ["泰国", "中国", "越南"], cables: "Asia Direct Cable (ADC) | SEA-H2X | Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "55 | 19 | 33 | 55", maxRisk: 55, avgRisk: 41, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度|埃及|印度 → 坦桑尼亚 → 埃及", from: "印度", to: "埃及", path: "印度 → 坦桑尼亚 → 埃及", nodes: ["印度", "坦桑尼亚", "埃及"], cables: "SEACOM | SEACOM", riskScores: "44 | 44", maxRisk: 44, avgRisk: 44, segments: 2, safety: "较优备选路径" as SafetyLevel },
  { id: "印度|马来西亚|印度 → 泰国 → 马来西亚", from: "印度", to: "马来西亚", path: "印度 → 泰国 → 马来西亚", nodes: ["印度", "泰国", "马来西亚"], cables: "MIST | SEA-H2X", riskScores: "47 | 19", maxRisk: 47, avgRisk: 33, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度|泰国|印度 → 泰国", from: "印度", to: "泰国", path: "印度 → 泰国", nodes: ["印度", "泰国"], cables: "MIST", riskScores: "47", maxRisk: 47, avgRisk: 47, segments: 1, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度|印度尼西亚|印度 → 泰国 → 印度尼西亚", from: "印度", to: "印度尼西亚", path: "印度 → 泰国 → 印度尼西亚", nodes: ["印度", "泰国", "印度尼西亚"], cables: "MIST | Thailand-Indonesia-Singapore (TIS)", riskScores: "47 | 33", maxRisk: 47, avgRisk: 40, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度|越南|印度 → 泰国 → 越南", from: "印度", to: "越南", path: "印度 → 泰国 → 越南", nodes: ["印度", "泰国", "越南"], cables: "MIST | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "47 | 55 | 30", maxRisk: 55, avgRisk: 44, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度|中国|印度 → 泰国 → 中国", from: "印度", to: "中国", path: "印度 → 泰国 → 中国", nodes: ["印度", "泰国", "中国"], cables: "MIST | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "47 | 55 | 19", maxRisk: 55, avgRisk: 40, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度尼西亚|马来西亚|印度尼西亚 → 菲律宾 → 马来西亚", from: "印度尼西亚", to: "马来西亚", path: "印度尼西亚 → 菲律宾 → 马来西亚", nodes: ["印度尼西亚", "菲律宾", "马来西亚"], cables: "Asia Connect Cable-1 (ACC-1) | MYUS | Asia Link Cable (ALC) | SEA-H2X | MYUS | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "61 | 61 | 50 | 36 | 61 | 71", maxRisk: 71, avgRisk: 57, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "印度尼西亚|马来西亚|印度尼西亚 → 马来西亚", from: "印度尼西亚", to: "马来西亚", path: "印度尼西亚 → 马来西亚", nodes: ["印度尼西亚", "马来西亚"], cables: "Dumai-Melaka Cable System (DMCS) | Batam Dumai Melaka (BDM) | Batam-Rengit Cable System (BRCS) | Batam Sarawak Internet Cable System (BaSICS)", riskScores: "33 | 19 | 30 | 30", maxRisk: 33, avgRisk: 28, segments: 1, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|马来西亚|印度尼西亚 → 泰国 → 马来西亚", from: "印度尼西亚", to: "马来西亚", path: "印度尼西亚 → 泰国 → 马来西亚", nodes: ["印度尼西亚", "泰国", "马来西亚"], cables: "Thailand-Indonesia-Singapore (TIS) | SEA-H2X", riskScores: "33 | 19", maxRisk: 33, avgRisk: 26, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|马来西亚|印度尼西亚 → 新加坡 → 马来西亚", from: "印度尼西亚", to: "马来西亚", path: "印度尼西亚 → 新加坡 → 马来西亚", nodes: ["印度尼西亚", "新加坡", "马来西亚"], cables: "Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA | Asia Link Cable (ALC)", riskScores: "33 | 33 | 33 | 30 | 33", maxRisk: 33, avgRisk: 32, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|泰国|印度尼西亚 → 菲律宾 → 泰国", from: "印度尼西亚", to: "泰国", path: "印度尼西亚 → 菲律宾 → 泰国", nodes: ["印度尼西亚", "菲律宾", "泰国"], cables: "Asia Connect Cable-1 (ACC-1) | MYUS | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "61 | 61 | 71 | 36", maxRisk: 71, avgRisk: 57, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "印度尼西亚|泰国|印度尼西亚 → 马来西亚 → 泰国", from: "印度尼西亚", to: "泰国", path: "印度尼西亚 → 马来西亚 → 泰国", nodes: ["印度尼西亚", "马来西亚", "泰国"], cables: "Dumai-Melaka Cable System (DMCS) | Batam Dumai Melaka (BDM) | Batam-Rengit Cable System (BRCS) | Batam Sarawak Internet Cable System (BaSICS) | SEA-H2X", riskScores: "33 | 19 | 30 | 30 | 19", maxRisk: 33, avgRisk: 26, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|泰国|印度尼西亚 → 泰国", from: "印度尼西亚", to: "泰国", path: "印度尼西亚 → 泰国", nodes: ["印度尼西亚", "泰国"], cables: "Thailand-Indonesia-Singapore (TIS)", riskScores: "33", maxRisk: 33, avgRisk: 33, segments: 1, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|泰国|印度尼西亚 → 新加坡 → 泰国", from: "印度尼西亚", to: "泰国", path: "印度尼西亚 → 新加坡 → 泰国", nodes: ["印度尼西亚", "新加坡", "泰国"], cables: "Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "33 | 33 | 33 | 30 | 33 | 55", maxRisk: 55, avgRisk: 36, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度尼西亚|越南|印度尼西亚 → 菲律宾 → 越南", from: "印度尼西亚", to: "越南", path: "印度尼西亚 → 菲律宾 → 越南", nodes: ["印度尼西亚", "菲律宾", "越南"], cables: "Asia Connect Cable-1 (ACC-1) | MYUS | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | ALPHA", riskScores: "61 | 61 | 50 | 71 | 61", maxRisk: 71, avgRisk: 61, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "印度尼西亚|越南|印度尼西亚 → 马来西亚 → 越南", from: "印度尼西亚", to: "越南", path: "印度尼西亚 → 马来西亚 → 越南", nodes: ["印度尼西亚", "马来西亚", "越南"], cables: "Dumai-Melaka Cable System (DMCS) | Batam Dumai Melaka (BDM) | Batam-Rengit Cable System (BRCS) | Batam Sarawak Internet Cable System (BaSICS) | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 19 | 30 | 30 | 33 | 30", maxRisk: 33, avgRisk: 29, segments: 2, safety: "相对低暴露优先路径" as SafetyLevel },
  { id: "印度尼西亚|越南|印度尼西亚 → 泰国 → 越南", from: "印度尼西亚", to: "越南", path: "印度尼西亚 → 泰国 → 越南", nodes: ["印度尼西亚", "泰国", "越南"], cables: "Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 55 | 30", maxRisk: 55, avgRisk: 39, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "印度尼西亚|越南|印度尼西亚 → 新加坡 → 越南", from: "印度尼西亚", to: "越南", path: "印度尼西亚 → 新加坡 → 越南", nodes: ["印度尼西亚", "新加坡", "越南"], cables: "Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 33 | 33 | 30 | 33 | 55 | 30", maxRisk: 55, avgRisk: 35, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|阿联酋|中国 → 新加坡 → 阿联酋", from: "中国", to: "阿联酋", path: "中国 → 新加坡 → 阿联酋", nodes: ["中国", "新加坡", "阿联酋"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | PEACE Cable", riskScores: "33 | 55 | 8", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|埃及|中国 → 新加坡 → 埃及", from: "中国", to: "埃及", path: "中国 → 新加坡 → 埃及", nodes: ["中国", "新加坡", "埃及"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | PEACE Cable", riskScores: "33 | 55 | 8", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 菲律宾 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 菲律宾 → 马来西亚", nodes: ["中国", "菲律宾", "马来西亚"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | SEA-H2X | Asia Link Cable (ALC) | SEA-H2X | MYUS | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "50 | 71 | 36 | 50 | 36 | 61 | 71", maxRisk: 71, avgRisk: 54, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 马来西亚", nodes: ["中国", "马来西亚"], cables: "Asia Link Cable (ALC) | SEA-H2X | BtoBE", riskScores: "33 | 19 | 44", maxRisk: 44, avgRisk: 32, segments: 1, safety: "较优备选路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 日本 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 日本 → 马来西亚", nodes: ["中国", "日本", "马来西亚"], cables: "Asia Direct Cable (ADC) | TGN-IA2 | Asia Submarine-cable Express (ASE)/Cahaya Malaysia", riskScores: "71 | 61 | 71", maxRisk: 71, avgRisk: 68, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 泰国 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 泰国 → 马来西亚", nodes: ["中国", "泰国", "马来西亚"], cables: "Asia Direct Cable (ADC) | SEA-H2X | SEA-H2X", riskScores: "55 | 19 | 19", maxRisk: 55, avgRisk: 31, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 新加坡 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 新加坡 → 马来西亚", nodes: ["中国", "新加坡", "马来西亚"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Asia Link Cable (ALC)", riskScores: "33 | 55 | 33", maxRisk: 55, avgRisk: 40, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|马来西亚|中国 → 越南 → 马来西亚", from: "中国", to: "马来西亚", path: "中国 → 越南 → 马来西亚", nodes: ["中国", "越南", "马来西亚"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 55 | 33 | 30", maxRisk: 55, avgRisk: 38, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|沙特阿拉伯|中国 → 新加坡 → 沙特阿拉伯", from: "中国", to: "沙特阿拉伯", path: "中国 → 新加坡 → 沙特阿拉伯", nodes: ["中国", "新加坡", "沙特阿拉伯"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | PEACE Cable", riskScores: "33 | 55 | 8", maxRisk: 55, avgRisk: 32, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 菲律宾 → 泰国", from: "中国", to: "泰国", path: "中国 → 菲律宾 → 泰国", nodes: ["中国", "菲律宾", "泰国"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | SEA-H2X | Asia Direct Cable (ADC) | SEA-H2X", riskScores: "50 | 71 | 36 | 71 | 36", maxRisk: 71, avgRisk: 53, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 马来西亚 → 泰国", from: "中国", to: "泰国", path: "中国 → 马来西亚 → 泰国", nodes: ["中国", "马来西亚", "泰国"], cables: "Asia Link Cable (ALC) | SEA-H2X | BtoBE | SEA-H2X", riskScores: "33 | 19 | 44 | 19", maxRisk: 44, avgRisk: 29, segments: 2, safety: "较优备选路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 日本 → 泰国", from: "中国", to: "泰国", path: "中国 → 日本 → 泰国", nodes: ["中国", "日本", "泰国"], cables: "Asia Direct Cable (ADC) | TGN-IA2 | Asia Direct Cable (ADC)", riskScores: "71 | 61 | 71", maxRisk: 71, avgRisk: 68, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 泰国", from: "中国", to: "泰国", path: "中国 → 泰国", nodes: ["中国", "泰国"], cables: "Asia Direct Cable (ADC) | SEA-H2X", riskScores: "55 | 19", maxRisk: 55, avgRisk: 37, segments: 1, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 新加坡 → 泰国", from: "中国", to: "泰国", path: "中国 → 新加坡 → 泰国", nodes: ["中国", "新加坡", "泰国"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Thailand-Indonesia-Singapore (TIS) | Asia Direct Cable (ADC)", riskScores: "33 | 55 | 33 | 55", maxRisk: 55, avgRisk: 44, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|泰国|中国 → 越南 → 泰国", from: "中国", to: "泰国", path: "中国 → 越南 → 泰国", nodes: ["中国", "越南", "泰国"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 55 | 55 | 30", maxRisk: 55, avgRisk: 43, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|印度尼西亚|中国 → 菲律宾 → 印度尼西亚", from: "中国", to: "印度尼西亚", path: "中国 → 菲律宾 → 印度尼西亚", nodes: ["中国", "菲律宾", "印度尼西亚"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | SEA-H2X | Asia Connect Cable-1 (ACC-1) | MYUS", riskScores: "50 | 71 | 36 | 61 | 61", maxRisk: 71, avgRisk: 56, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|印度尼西亚|中国 → 马来西亚 → 印度尼西亚", from: "中国", to: "印度尼西亚", path: "中国 → 马来西亚 → 印度尼西亚", nodes: ["中国", "马来西亚", "印度尼西亚"], cables: "Asia Link Cable (ALC) | SEA-H2X | BtoBE | Dumai-Melaka Cable System (DMCS) | Batam Dumai Melaka (BDM) | Batam-Rengit Cable System (BRCS) | Batam Sarawak Internet Cable System (BaSICS)", riskScores: "33 | 19 | 44 | 33 | 19 | 30 | 30", maxRisk: 44, avgRisk: 30, segments: 2, safety: "较优备选路径" as SafetyLevel },
  { id: "中国|印度尼西亚|中国 → 泰国 → 印度尼西亚", from: "中国", to: "印度尼西亚", path: "中国 → 泰国 → 印度尼西亚", nodes: ["中国", "泰国", "印度尼西亚"], cables: "Asia Direct Cable (ADC) | SEA-H2X | Thailand-Indonesia-Singapore (TIS)", riskScores: "55 | 19 | 33", maxRisk: 55, avgRisk: 36, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|印度尼西亚|中国 → 新加坡 → 印度尼西亚", from: "中国", to: "印度尼西亚", path: "中国 → 新加坡 → 印度尼西亚", nodes: ["中国", "新加坡", "印度尼西亚"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Indonesia Global Gateway (IGG) System | Thailand-Indonesia-Singapore (TIS) | Batam Singapore Cable System (BSCS) | INSICA", riskScores: "33 | 55 | 33 | 33 | 33 | 30", maxRisk: 55, avgRisk: 36, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|越南|中国 → 菲律宾 → 越南", from: "中国", to: "越南", path: "中国 → 菲律宾 → 越南", nodes: ["中国", "菲律宾", "越南"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | SEA-H2X | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | ALPHA", riskScores: "50 | 71 | 36 | 50 | 71 | 61", maxRisk: 71, avgRisk: 57, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|越南|中国 → 马来西亚 → 越南", from: "中国", to: "越南", path: "中国 → 马来西亚 → 越南", nodes: ["中国", "马来西亚", "越南"], cables: "Asia Link Cable (ALC) | SEA-H2X | BtoBE | Asia Link Cable (ALC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 19 | 44 | 33 | 30", maxRisk: 44, avgRisk: 32, segments: 2, safety: "较优备选路径" as SafetyLevel },
  { id: "中国|越南|中国 → 日本 → 越南", from: "中国", to: "越南", path: "中国 → 日本 → 越南", nodes: ["中国", "日本", "越南"], cables: "Asia Direct Cable (ADC) | TGN-IA2 | Asia Direct Cable (ADC) | ALPHA", riskScores: "71 | 61 | 71 | 61", maxRisk: 71, avgRisk: 66, segments: 2, safety: "高暴露路径" as SafetyLevel },
  { id: "中国|越南|中国 → 泰国 → 越南", from: "中国", to: "越南", path: "中国 → 泰国 → 越南", nodes: ["中国", "泰国", "越南"], cables: "Asia Direct Cable (ADC) | SEA-H2X | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "55 | 19 | 55 | 30", maxRisk: 55, avgRisk: 40, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|越南|中国 → 新加坡 → 越南", from: "中国", to: "越南", path: "中国 → 新加坡 → 越南", nodes: ["中国", "新加坡", "越南"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Asia Link Cable (ALC) | Asia Direct Cable (ADC) | Vietnam-Singapore Cable System (VTS)", riskScores: "33 | 55 | 33 | 55 | 30", maxRisk: 55, avgRisk: 41, segments: 2, safety: "中等暴露路径" as SafetyLevel },
  { id: "中国|越南|中国 → 越南", from: "中国", to: "越南", path: "中国 → 越南", nodes: ["中国", "越南"], cables: "Asia Link Cable (ALC) | Asia Direct Cable (ADC)", riskScores: "33 | 55", maxRisk: 55, avgRisk: 44, segments: 1, safety: "中等暴露路径" as SafetyLevel },
];
