// src/lib/tooltips.ts
// 所有悬停提示的文案 — 中英双语
// 设计原则：客观、理性、信息密度高、不带政治立场

export const TOOLTIPS = {
  en: {
    // ═══ 风险评分因子 ═══
    riskOverall: 'Composite geopolitical risk score (0-100) calculated from 7 weighted factors. Higher score indicates greater exposure to non-technical disruption risks. Updated periodically based on publicly available data.',
    riskConflict: 'Conflict Waters (25% weight): Measures whether the cable route passes through waters with active armed conflicts, territorial disputes, or documented hostile naval activities. Based on open-source maritime security reports.',
    riskSanctions: 'Sanctions Risk (20% weight): Assesses whether the cable connects countries subject to international economic sanctions. Sanctioned jurisdictions may face restrictions on cable maintenance, spare parts, or financial transactions related to cable operations.',
    riskMilitary: 'Military Activity (15% weight): Evaluates the density of military deployments and exercises along the cable route. High military activity zones increase the probability of accidental anchor damage or intentional interference.',
    riskOwnership: 'Ownership Concentration (15% weight): Measures the diversity of cable ownership. A cable owned by a single entity is more vulnerable to single-point-of-failure risks. Diversified ownership (3+ owners) provides better resilience.',
    riskLegal: 'Legal Complexity (10% weight): Counts the number of sovereign jurisdictions the cable passes through. More jurisdictions mean more permits required for repair operations, potentially increasing restoration time after a fault.',
    riskHistorical: 'Historical Damage (10% weight): Based on ICPC data showing ~200 cable faults per year globally. This factor reflects the historical fault frequency in the geographic region where the cable is routed. 70-80% of faults are caused by fishing and anchoring.',
    riskEvents: 'Recent Events (5% weight): Reflects whether there have been security incidents in the cable\'s operating area within the past 6 months. This is the most dynamic factor and will be enhanced with real-time GDELT data in future updates.',

    // ═══ 风险等级 ═══
    riskCritical: 'Critical Risk (75-100): The cable route traverses multiple active conflict zones or connects heavily sanctioned countries. Heightened probability of service disruption from non-technical causes.',
    riskHigh: 'High Risk (55-74): Significant geopolitical exposure. The cable passes through at least one conflict zone or connects sanctioned jurisdictions.',
    riskElevated: 'Elevated Risk (35-54): Moderate geopolitical factors present. May include concentrated ownership or high historical fault rates in the region.',
    riskModerate: 'Moderate Risk (15-34): Limited geopolitical exposure. Standard operational risks apply.',
    riskLow: 'Low Risk (0-14): Minimal geopolitical risk factors. The cable operates in stable, well-governed maritime zones with diversified ownership.',

    // ═══ 地震相关 ═══
    earthquake: 'Real-time earthquake data from the U.S. Geological Survey (USGS). Shows M4.5+ earthquakes from the past 7 days. The system automatically calculates the distance between each earthquake and nearby submarine cable routes to assess potential impact.',
    eqMagnitude: 'Earthquake magnitude on the Richter scale. M5.0-5.9: moderate, may cause cable vibration. M6.0-6.9: strong, potential for cable displacement. M7.0+: major, high risk of cable damage or seabed landslides.',
    eqRiskHigh: 'HIGH: The earthquake epicenter is within 30% of the calculated impact radius of this cable. Immediate monitoring recommended.',
    eqRiskMedium: 'MEDIUM: The earthquake is within the impact radius but at moderate distance. Monitoring advised.',
    eqRiskLow: 'LOW: The earthquake is near the edge of the impact radius. Low probability of cable damage.',
    eqDepth: 'Earthquake depth in kilometers below the surface. Shallow earthquakes (<70km) are more likely to cause seabed disruption. Deep earthquakes (>300km) rarely affect submarine cables.',

    // ═══ AI分析 ═══
    aiInsights: 'Toggle AI-inferred content on/off. When ON, the platform displays intelligence generated by AI analysis (marked with blue pulse indicators). When OFF, only verified factual data from official sources is shown. This implements the Fact/Inference Separation Principle.',
    aiConfidence: 'AI confidence score (0-100%) indicates how certain the model is about its analysis. >90%: high confidence, well-supported by source text. 60-89%: moderate, some ambiguity in the source. <60%: low confidence, treat as preliminary.',
    aiSeverity: 'Event severity scale (1-5). Level 1: minor industry news. Level 2: policy or regulatory development. Level 3: construction delay or moderate issue. Level 4: partial fault or significant repair needed. Level 5: complete cable break affecting international traffic.',

    // ═══ 海缆属性 ═══
    cableLength: 'Total route length of the submarine cable in kilometers, measured along the seabed path. Longer cables generally have higher fault probability and longer repair times.',
    cableRFS: 'Ready for Service date — when the cable entered (or is expected to enter) commercial operation.',
    cableServiceYears: 'Years since the cable entered service. Most submarine cables have a design lifespan of 25 years. Cables approaching end-of-life may experience higher fault rates.',
    cableCapacity: 'Design capacity in Terabits per second (Tbps). Modern cables (2020+) typically offer 100+ Tbps. Older cables may have significantly lower capacity.',
    cableFiberPairs: 'Number of optical fiber pairs in the cable. Each fiber pair can carry independent traffic. More fiber pairs provide greater capacity and redundancy.',
    cableLifespan: 'Progress bar showing how much of the cable\'s estimated 25-year design lifespan has elapsed. Cables past 80% may require planning for replacement.',

    // ═══ 颜色模式 ═══
    colorStatus: 'Color cables by operational status: green = in service, amber = under construction, blue = planned, gray = decommissioned.',
    colorVendor: 'Color cables by the company that manufactured and installed them. The top 8 vendors by cable count each have a unique color.',
    colorOperator: 'Color cables by the company that owns and operates them. The top 8 operators each have a unique color. Many cables have multiple owners.',
    colorAge: 'Color cables by the decade they entered service. Gray = before 2000, amber = 2000s, blue = 2010s, green = 2020s, purple = planned future.',

    // ═══ 信号源 ═══
    signalNews: 'News signal: monitors industry news from SubTel Forum and Submarine Networks via RSS feeds. AI (MiniMax) analyzes each article to extract structured intelligence about cable events.',
    signalBGP: 'BGP signal: monitors Border Gateway Protocol routing data via RIPE Stat. Changes in BGP routing paths can indicate that traffic is being rerouted due to a cable fault.',
    signalTraffic: 'Traffic signal: monitors internet traffic flow data via IODA (Georgia Tech). A sudden drop in traffic to/from a country may indicate that a submarine cable serving that country has failed.',
  },

  zh: {
    // ═══ 风险评分因子 ═══
    riskOverall: '综合地缘政治风险评分（0-100），由7个加权因子计算得出。分数越高，表示该海缆面临的非技术性中断风险越大。基于公开数据定期更新。',
    riskConflict: '冲突水域（权重25%）：评估海缆路由是否经过存在武装冲突、领土争端或有记录的敌对海军活动的水域。数据基于公开海事安全报告。',
    riskSanctions: '制裁风险（权重20%）：评估海缆是否连接受国际经济制裁的国家。受制裁地区可能面临海缆维护、备件供应或运营相关金融交易的限制。',
    riskMilitary: '军事活动（权重15%）：评估海缆路由沿线的军事部署和演习密度。高军事活动区域增加了意外锚损或蓄意干扰的概率。',
    riskOwnership: '所有权集中度（权重15%）：衡量海缆所有权的多元化程度。由单一实体拥有的海缆更容易面临单点故障风险。多元化所有权（3个以上拥有者）提供更好的韧性。',
    riskLegal: '法律复杂度（权重10%）：统计海缆经过的主权管辖区数量。管辖区越多，维修操作所需的许可证越多，故障后的修复时间可能越长。',
    riskHistorical: '历史破坏记录（权重10%）：基于国际海缆保护委员会（ICPC）数据，全球每年约发生200起海缆故障。该因子反映海缆所在地理区域的历史故障频率。70-80%的故障由渔业活动和船舶抛锚造成。',
    riskEvents: '近期事件活跃度（权重5%）：反映海缆运营区域在过去6个月内是否发生过安全事件。这是最动态的因子，未来将通过接入GDELT实时数据进一步增强。',

    // ═══ 风险等级 ═══
    riskCritical: '极高风险（75-100）：海缆路由穿越多个活跃冲突区域，或连接受严重制裁的国家。因非技术原因导致服务中断的概率较高。',
    riskHigh: '高风险（55-74）：存在显著的地缘政治风险敞口。海缆经过至少一个冲突区域或连接受制裁管辖区。',
    riskElevated: '中高风险（35-54）：存在中等程度的地缘政治因素。可能包括所有权集中度高或该区域历史故障率高。',
    riskModerate: '中等风险（15-34）：地缘政治风险敞口有限。适用标准运营风险。',
    riskLow: '低风险（0-14）：地缘政治风险因素极少。海缆在稳定、治理良好的海域运营，且所有权多元化。',

    // ═══ 地震相关 ═══
    earthquake: '来自美国地质调查局（USGS）的实时地震数据，展示过去7天内全球4.5级以上的地震。系统自动计算每次地震与附近海缆路由之间的距离，评估潜在影响。',
    eqMagnitude: '里氏震级。5.0-5.9级：中等强度，可能引起海缆振动。6.0-6.9级：强烈，可能导致海缆位移。7.0级以上：重大地震，海缆损坏或海底滑坡的风险较高。',
    eqRiskHigh: '高风险：震中位于该海缆计算影响半径的30%以内。建议立即监控。',
    eqRiskMedium: '中等风险：地震位于影响半径内但距离适中。建议保持关注。',
    eqRiskLow: '低风险：地震位于影响半径的边缘附近。海缆受损概率较低。',
    eqDepth: '地震深度（单位：公里）。浅源地震（<70公里）更容易引起海底扰动。深源地震（>300公里）极少影响海底光缆。',

    // ═══ AI分析 ═══
    aiInsights: '开启/关闭AI推断内容。开启时，平台显示AI分析生成的情报（以蓝色脉冲指示器标记）。关闭时，仅显示来自官方数据源的已验证事实数据。这是「事实/推断分离原则」的核心实现。',
    aiConfidence: 'AI置信度（0-100%）：表示模型对其分析结果的确信程度。>90%：高置信度，源文本充分支持。60-89%：中等置信度，源文本存在一定歧义。<60%：低置信度，应视为初步判断。',
    aiSeverity: '事件严重程度（1-5级）。1级：一般行业新闻。2级：政策或监管动态。3级：施工延期或中等程度问题。4级：部分故障或需要重大维修。5级：海缆完全断裂，影响国际流量。',

    // ═══ 海缆属性 ═══
    cableLength: '海底光缆的总路由长度（公里），沿海底路径测量。较长的海缆通常具有较高的故障概率和较长的维修时间。',
    cableRFS: '投产日期（Ready for Service）——海缆进入（或预计进入）商业运营的时间。',
    cableServiceYears: '海缆投入使用的年数。大多数海底光缆的设计寿命为25年。接近使用寿命末期的海缆可能故障率升高。',
    cableCapacity: '设计容量，单位为太比特每秒（Tbps）。2020年后建造的现代海缆通常提供100+ Tbps的容量。较早期的海缆容量可能显著较低。',
    cableFiberPairs: '光缆中的光纤对数。每对光纤可以承载独立的流量。更多的光纤对提供更大的容量和冗余能力。',
    cableLifespan: '进度条显示海缆预计25年设计寿命已经过了多少。超过80%的海缆可能需要考虑更换计划。',

    // ═══ 颜色模式 ═══
    colorStatus: '按运营状态着色：绿色=在役，琥珀色=在建，蓝色=规划中，灰色=已退役。',
    colorVendor: '按建造商着色。按海缆数量排名前8的建造商各有唯一颜色。',
    colorOperator: '按运营商着色。排名前8的运营商各有唯一颜色。许多海缆有多个运营商。',
    colorAge: '按投产年代着色。灰色=2000年以前，琥珀色=2000年代，蓝色=2010年代，绿色=2020年代，紫色=未来规划。',

    // ═══ 信号源 ═══
    signalNews: '新闻信号：通过RSS订阅监测SubTel Forum和Submarine Networks的行业新闻。AI（MiniMax）分析每篇文章，提取有关海缆事件的结构化情报。',
    signalBGP: 'BGP信号：通过RIPE Stat监测边界网关协议路由数据。BGP路由路径的变化可能表明流量正因海缆故障而被重新路由。',
    signalTraffic: '流量信号：通过IODA（佐治亚理工学院）监测互联网流量数据。某个国家的流量突然下降可能表明为该国提供服务的海底光缆发生了故障。',
  },
};

// 获取当前语言的提示文案
export function getTooltip(key: string, locale: string): string {
  const dict = locale === 'zh' ? TOOLTIPS.zh : TOOLTIPS.en;
  return (dict as any)[key] || '';
}
